default:
    use-mysql: false
    mysql-hostname: localhost
    mysql-port: 3306
    mysql-database: minecraft
    mysql-username: root
    mysql-password: root
achievements:
    enabled: true
    broadcast: true
    message: '&5[&6Achievement Earned&5] &c#name#&6! #message#'
    broadcast-message: '&5[&6Achievements&5] &c#player# &6just earned the achievement &5#name#&5!'