name: SGStats
main: com.sgcraft.sgstats.SGStats
author: SGCraft
version: 0.1
depend: [Vault]
commands:
  achv:
    description: View achievements
    usage: /<command> <help>
  stat:
    description: View your stats
    usage: /<command> <help>